from django.urls import path
from . import views
from .views import auth, library, manage, ranks, registration

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('action/', views.action, name='action'),
    path('quiz/', views.quiz_start, name='quiz_start'),
    path('quiz/<int:attempt_id>/', views.quiz_take, name='quiz_take'),
    path('quiz/<int:attempt_id>/review/', views.quiz_review, name='quiz_review'),
    path('export.xlsx', views.export_excel, name='export_excel'),
    path('ranks/', ranks.ranks, name='ranks'),
    path('library/', library.library, name='library'),
    path('library/add/', library.book_add, name='book_add'),
    path('library/tool/', library.book_tool, name='book_tool'),
    path('library/<int:pk>/', library.book_detail, name='book_detail'),
    path('library/<int:pk>/edit/', library.book_edit, name='book_edit'),
    path('manage/import/', manage.manage_import, name='manage_import'),
    path('manage/teachers/', manage.manage_teachers, name='manage_teachers'),
    path('login/', auth.login_hub, name='login'),
    path('register/', registration.register_hub, name='register'),
    path('register/teacher/', registration.teacher_register, name='teacher_register'),
    path('register/parent/', registration.parent_register, name='parent_register'),
    path('login/staff/', auth.staff_login, name='staff_login'),
    path('logout/', auth.logout, name='logout'),
    path('accounts/password/', auth.staff_password, name='staff_password'),
    path('student/login/', auth.student_login, name='student_login'),
    path('student/login/<int:classroom_id>/', auth.student_pick, name='student_pick'),
    path('student/', auth.student_home, name='student_home'),
    path('student/password/', auth.student_password, name='student_password'),
    path('student/goal/', auth.student_goal, name='student_goal'),
    path('student/pet/', auth.student_pet, name='student_pet'),
    path('shelf/', auth.shelf, name='shelf'),
    path('shelf/change/', auth.shelf_change, name='shelf_change'),
    path('parent/login/', auth.parent_login, name='parent_login'),
    path('parent/', auth.parent_home, name='parent_home'),
    path('parent/bind/', registration.parent_bind, name='parent_bind'),
    path('parent/switch/', registration.parent_switch, name='parent_switch'),
    path('parent/password/', auth.parent_password, name='parent_password'),
    path('accounts/', registration.student_accounts, name='student_accounts'),
    path('accounts/student/<int:student_id>/', registration.student_account_action, name='student_account_action'),
    path('manage/accounts/', registration.account_approvals, name='account_approvals'),
    path('organizations/', registration.organization_manage, name='organization_manage'),
    path('organizations/switch/', registration.organization_switch, name='organization_switch'),
]
