# Generated by Django 6.0.8 on 2026-09-11 06:10

import reading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=reading.models.grade_choices, db_index=True, default=1),
        ),
    ]
