# Generated by Django 6.0.8 on 2026-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_classroom_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='atos',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
    ]
