# Generated by Django 6.0.8 on 2026-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_book_atos_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
