# Generated by Django 6.0.8 on 2026-09-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_book_author_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
