# Generated by Django 6.0.8 on 2026-09-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_quizattempt_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to='reading.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'book')},
            },
        ),
    ]
