# Generated by Django 6.0.8 on 2026-09-16 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_student_codes(apps, schema_editor):
    Student = apps.get_model('reading', 'Student')
    for student in Student.objects.all():
        student.login_id = f'S{student.pk:05d}'
        student.bind_code = f'B{student.pk:07d}'
        student.save(update_fields=['login_id', 'bind_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_shelfitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bind_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(fill_student_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('manager', 'Manager'), ('parent', 'Parent')], default='teacher', max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=20)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='reading.student')),
            ],
            options={
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
