# Generated by Django 6.0.8 on 2026-09-16 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_staff_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('reading', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(
            user=user, role='manager' if user.is_superuser else 'teacher', approved=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_registration_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(fill_staff_profiles, migrations.RunPython.noop),
    ]
