# Generated by Django 6.0.8 on 2026-09-16 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_organization(apps, schema_editor):
    Organization = apps.get_model('reading', 'Organization')
    Membership = apps.get_model('reading', 'Membership')
    Classroom = apps.get_model('reading', 'Classroom')
    TeacherInvite = apps.get_model('reading', 'TeacherInvite')
    AccountAudit = apps.get_model('reading', 'AccountAudit')
    Profile = apps.get_model('reading', 'Profile')
    organization = Organization.objects.create(
        name='Beijing Aidi School 北京爱迪学校', slug='beijing-aidi-school'
    )
    Classroom.objects.update(organization=organization)
    TeacherInvite.objects.update(organization=organization)
    AccountAudit.objects.update(organization=organization)
    for profile in Profile.objects.filter(role__in=('teacher', 'manager')).select_related('user'):
        Membership.objects.create(
            user=profile.user, organization=organization,
            role=profile.role, active=profile.approved and profile.user.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_account_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountaudit',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_audits', to='reading.organization'),
        ),
        migrations.AddField(
            model_name='book',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reading.organization'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='reading.organization'),
        ),
        migrations.AddField(
            model_name='teacherinvite',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invites', to='reading.organization'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('manager', 'Manager')], default='teacher', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='reading.organization')),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(create_default_organization, migrations.RunPython.noop),
    ]
