# Generated by Django 6.0.8 on 2026-09-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series_order',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
