# Generated by Django 6.0.8 on 2026-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0014_student_personal_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
